# Generated by Django 2.2.6 on 2019-11-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENG', models.IntegerField()),
                ('MAT', models.IntegerField()),
                ('SCI', models.IntegerField()),
                ('PERCENTAGE', models.IntegerField()),
            ],
        ),
    ]
